### ISSUE TITLE
How do I update the Blazor app after making changes?

### ISSUE THREAD

**Issue by davghouse** [ao-ladderer/ao-ladderer.github.io#1]
Would you mind explaining how to update the Blazor app after making changes to AO Ladderer?

**Comment by galehouse5** [comment]
1. Publish Blazor project to a folder. Just accept Visual Studio defaults for advanced settings (Configuration: Release, Target Framework: netstandard2.0, Target Runtime: Portable).
![image](https://user-images.githubusercontent.com/1687988/49339719-ddb8a300-f603-11e8-9dde-1f78cff80030.png)
2. Copy contents of publish folder (`AOladderer.Blazor/dist` subfolder actually) over top your [ao-ladderer.github.io](https://github.com/ao-ladderer/ao-ladderer.github.io) working copy, overwriting files.
![image](https://user-images.githubusercontent.com/1687988/49339838-59ffb600-f605-11e8-996d-6b6a751a3ded.png)
![image](https://user-images.githubusercontent.com/1687988/49339847-7865b180-f605-11e8-9f15-204c265bd2f5.png)
3. Revert changes to `index.html` (usually), which contains customizations for hosting on GitHub Pages, then commit and push your [ao-ladderer.github.io](https://github.com/ao-ladderer/ao-ladderer.github.io) working copy.
![image](https://user-images.githubusercontent.com/1687988/49339869-c4185b00-f605-11e8-92ed-869334eadeb2.png)
4. Wait a few minutes for GitHub Pages to publish your changes to its CDN and then they'll be live at https://ao-ladderer.github.io.

**Comment by davghouse** [comment]
Thanks!
